#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar on laptop
polybar -r laptop-top &
polybar -r laptop-bottom &

# Launch bar on external monitor (USB-C or HDMI)
my_laptop_external_monitor=$(xrandr -q | grep -v '^e' | grep DP1)
if [[ $my_laptop_external_monitor = *connected* ]]; then
    polybar -r external-top &
    polybar -r external-bottom &

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI1 connected')
elif [[ $my_laptop_external_monitor = *connected* ]]; then
    polybar -r external-top &
    polybar -r external-bottom &
fi
